In [3]:
import tensorflow as tf
import numpy as np

## Initialization of Tensors

In [26]:
x = tf.constant(4)
x

<tf.Tensor: id=57, shape=(), dtype=int32, numpy=4>

In [5]:
x = tf.constant(4.0)
x

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=4.0>

In [6]:
x = tf.constant(4, shape = (1, 1), dtype = tf.float32)
x

<tf.Tensor: id=4, shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x

<tf.Tensor: id=5, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [8]:
x = tf.ones(shape = (3, 3))
x

<tf.Tensor: id=8, shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
x = tf.zeros(shape = (4, 4))
x

<tf.Tensor: id=14, shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [13]:
x = tf.eye(3)   # Identity Matrix
x

<tf.Tensor: id=22, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [14]:
x = tf.random.normal((3, 3), mean = 0, stddev = 1)
x

<tf.Tensor: id=28, shape=(3, 3), dtype=float32, numpy=
array([[ 0.28467533, -0.6931985 ,  2.1053147 ],
       [-0.578272  , -1.5165507 ,  0.04383931],
       [-1.7303865 , -1.8668606 ,  1.1176459 ]], dtype=float32)>

In [16]:
x = tf.random.uniform((1, 3), minval = 0, maxval = 1)
x

<tf.Tensor: id=35, shape=(1, 3), dtype=float32, numpy=array([[0.25608432, 0.5327635 , 0.36854076]], dtype=float32)>

In [23]:
x = tf.range(start = 0, limit = 21, delta = 5)
x

<tf.Tensor: id=55, shape=(5,), dtype=int32, numpy=array([ 0,  5, 10, 15, 20])>

In [25]:
x = tf.cast(x, dtype = tf.float64)
x

<tf.Tensor: id=56, shape=(5,), dtype=float64, numpy=array([ 0.,  5., 10., 15., 20.])>

## Mathematical Operations

In [27]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)

In [28]:
z

<tf.Tensor: id=60, shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [29]:
tf.multiply(x, y)

<tf.Tensor: id=61, shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>

In [30]:
tf.subtract(x, y)

<tf.Tensor: id=62, shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [31]:
tf.divide(x, y)

<tf.Tensor: id=65, shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [34]:
tf.tensordot(x, y, axes = 1)

<tf.Tensor: id=76, shape=(), dtype=int32, numpy=46>

In [35]:
tf.reduce_sum(x * y, axis = 0)

<tf.Tensor: id=79, shape=(), dtype=int32, numpy=46>

In [36]:
x ** y

<tf.Tensor: id=80, shape=(3,), dtype=int32, numpy=array([   1,  256, 2187])>

In [39]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z = tf.matmul(x, y)
z

<tf.Tensor: id=107, shape=(2, 4), dtype=float32, numpy=
array([[ 0.3443725 , -1.3556857 ,  0.34932062,  0.00354519],
       [-0.8492188 ,  1.2577608 , -0.11256983,  0.65980405]],
      dtype=float32)>

## Indexing

In [48]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[-1])
print(x[1:4])
print(x[::3])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 1 2], shape=(3,), dtype=int32)
tf.Tensor([0 2 2], shape=(3,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [50]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0][1])
print(x[2][:])

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


## Reshape Tensor

In [56]:
x = tf.range(8)
x

<tf.Tensor: id=286, shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7])>

In [58]:
x = tf.reshape(x, (2, 4))
x

<tf.Tensor: id=290, shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])>

In [59]:
x = tf.transpose(x, perm = [1, 0])
x

<tf.Tensor: id=292, shape=(4, 2), dtype=int32, numpy=
array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])>